In [92]:
# 1. Import the NUMPY package under the name np.

In [93]:
import numpy as np

In [94]:
#2. Print the NUMPY version and the configuration.

In [95]:
print("NumPy version:", np.__version__)
print("NumPy configuration:")
np.show_config()

NumPy version: 1.21.5
NumPy configuration:
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/JGR/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/JGR/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/JGR/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/JGR/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/JGR/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/JGR/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/JGR/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/JGR/opt/anaconda3/include']
Supported SIMD extensions in this NumPy insta

In [96]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. 
#How many ways can you find?


In [97]:
#PRIMERA MANERA DE HACER ARRAYS: usando random.rand()
a = np.random.rand(2,3,5)
print(a)

[[[0.05276228 0.47579539 0.92914121 0.92522001 0.76448382]
  [0.7565371  0.67894691 0.48610864 0.43537686 0.83501545]
  [0.09503612 0.11814708 0.74502839 0.61219845 0.15306194]]

 [[0.95025203 0.52618349 0.4338092  0.12150186 0.42011932]
  [0.18398431 0.39484728 0.62422238 0.01657707 0.59240813]
  [0.1173693  0.84127197 0.83210053 0.62931332 0.25466267]]]


In [98]:
# SEGUNDA MANERA DE HACER ARRAYS: usando random.ramdon()

m = np.random.random((2,3,5))

m

array([[[0.95002872, 0.8747619 , 0.04956069, 0.307233  , 0.7880073 ],
        [0.90516052, 0.72415957, 0.5915554 , 0.52448607, 0.09751174],
        [0.63224918, 0.51899782, 0.33195472, 0.14892873, 0.48196328]],

       [[0.94263532, 0.14345043, 0.14950076, 0.86432311, 0.24688852],
        [0.10169339, 0.18339224, 0.57658077, 0.72821057, 0.04365539],
        [0.25812954, 0.34934629, 0.91467176, 0.60694566, 0.3280531 ]]])

In [99]:
# TERCERA MANERA DE HACER ARRAYS: usando random.randint(numeros de primero al ultimo , size = (see below))

arr = np.random.randint(1, 100, size=(2, 3, 5))
arr

array([[[80, 49, 40, 96, 20],
        [39, 98, 13, 26, 96],
        [90, 49, 63, 50, 19]],

       [[99, 12, 14, 39,  1],
        [37, 25, 42, 61, 45],
        [11, 27, 76, 77, 32]]])

In [100]:
#4. Print a.

In [101]:
a

array([[[0.05276228, 0.47579539, 0.92914121, 0.92522001, 0.76448382],
        [0.7565371 , 0.67894691, 0.48610864, 0.43537686, 0.83501545],
        [0.09503612, 0.11814708, 0.74502839, 0.61219845, 0.15306194]],

       [[0.95025203, 0.52618349, 0.4338092 , 0.12150186, 0.42011932],
        [0.18398431, 0.39484728, 0.62422238, 0.01657707, 0.59240813],
        [0.1173693 , 0.84127197, 0.83210053, 0.62931332, 0.25466267]]])

In [102]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

In [132]:
b = np.full((5,2,3),1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [104]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [111]:
sizeA = np.size(a)
print("The size of a is:", sizeA)
 


The size of a is: 30


In [112]:
sizeB = np.size(b)
print("The size of b is", sizeB)

The size of b is 30


In [106]:
#8. Are you able to add a and b? Why or why not?

In [48]:
'''
You cannot add them in this case because (a and b) have not the same shape, even though they have the same size.
'''

'\nYou cannot add them in this case because (a and b) have not the same shape, even though they have the same size.\n'

In [113]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [133]:
c = b.reshape(2,3,5)

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [134]:
d = a+c


print(d)

"""
Now it works, as it has the same shape of a. So they can be added.
"""

[[[1.18174686 1.97464113 1.81275516 1.72997527 1.35117855]
  [1.96666791 1.28135561 1.89698318 1.99163132 1.85749486]
  [1.89383796 1.23564321 1.67597432 1.70225224 1.77625629]]

 [[1.17186779 1.02086494 1.57011851 1.88411295 1.40597257]
  [1.36974188 1.99370291 1.20967232 1.39236755 1.66463046]
  [1.10695364 1.01153378 1.43664868 1.29227245 1.34900605]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [135]:
print(a)

[[[0.18174686 0.97464113 0.81275516 0.72997527 0.35117855]
  [0.96666791 0.28135561 0.89698318 0.99163132 0.85749486]
  [0.89383796 0.23564321 0.67597432 0.70225224 0.77625629]]

 [[0.17186779 0.02086494 0.57011851 0.88411295 0.40597257]
  [0.36974188 0.99370291 0.20967232 0.39236755 0.66463046]
  [0.10695364 0.01153378 0.43664868 0.29227245 0.34900605]]]


In [137]:
print(d)

[[[1.18174686 1.97464113 1.81275516 1.72997527 1.35117855]
  [1.96666791 1.28135561 1.89698318 1.99163132 1.85749486]
  [1.89383796 1.23564321 1.67597432 1.70225224 1.77625629]]

 [[1.17186779 1.02086494 1.57011851 1.88411295 1.40597257]
  [1.36974188 1.99370291 1.20967232 1.39236755 1.66463046]
  [1.10695364 1.01153378 1.43664868 1.29227245 1.34900605]]]


In [ ]:
"""
Yes, its been aded the (1) to all of them. 

"""

In [ ]:
#12. Multiply a and c. Assign the result to e.

In [139]:
e = a * c
print(e)

[[[0.18174686 0.97464113 0.81275516 0.72997527 0.35117855]
  [0.96666791 0.28135561 0.89698318 0.99163132 0.85749486]
  [0.89383796 0.23564321 0.67597432 0.70225224 0.77625629]]

 [[0.17186779 0.02086494 0.57011851 0.88411295 0.40597257]
  [0.36974188 0.99370291 0.20967232 0.39236755 0.66463046]
  [0.10695364 0.01153378 0.43664868 0.29227245 0.34900605]]]


In [ ]:
#13. Does e equal to a? Why or why not?  - NO, BECAUSE MILTIPLY BY 1 ITS THE SAME NUMBER THAT ITS GIVEN INNITALLY 

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [140]:
d_max = d.max()
print(d_max)

1.9937029130160848


In [141]:
d_min = d.min()
print(d_min)

1.0115337834133018


In [142]:
d_mean = d.mean()
print(d_mean)

1.5402620120937363


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [146]:
d = np.random.rand(2, 3, 5)

# Create an empty array f with the same shape as d
f = np.empty_like(d)

# Print the array f
print(f)

[[[0.90323868 0.86047311 0.21318783 0.14684106 0.20706579]
  [0.56743278 0.86175777 0.5200664  0.20235376 0.43968065]
  [0.80834829 0.9018274  0.59016818 0.72382573 0.71498416]]

 [[0.93753581 0.65336922 0.10160103 0.50259697 0.20690856]
  [0.03822931 0.19333191 0.83217541 0.93060482 0.95142824]
  [0.34374862 0.2269319  0.53539423 0.86532788 0.38683816]]]


In [153]:
# Calculate d_min, d_mean, and d_max
d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100


In [ ]:
#17. Print d and f. Do you have your expected f?

In [152]:
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[0.59635784 0.16446482 0.11134683 0.13245511 0.46005183]
  [0.81023381 0.17707843 0.99546291 0.47089567 0.91032225]
  [0.438677   0.30723276 0.45787478 0.95697117 0.88387312]]

 [[0.3777955  0.74895673 0.79781713 0.40198674 0.09060545]
  [0.0954506  0.25185495 0.82575809 0.98850976 0.24739316]
  [0.54027641 0.19316564 0.15330385 0.11707778 0.82233845]]]
Array f:
 [[[ 75.  25.  25.  25.  25.]
  [ 75.  25. 100.  25.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 25.  75.  75.  25.   0.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  25.  25.  75.]]]


In [156]:
d = np.random.rand(2, 3, 5)

# Create an empty array f with the same shape as d
f = np.empty_like(d, dtype=str)

# Define mappings of values to string labels
mapping = {
    0: "A",
    25: "B",
    50: "C",
    75: "D",
    100: "E"}

# Calculate d_min, d_mean, and d_max
d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

# Iterate through each element in d and assign string labels to f based on the conditions
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = mapping[25]
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = mapping[75]
            elif d[i, j, k] == d_mean:
                f[i, j, k] = mapping[50]
            elif d[i, j, k] == d_min:
                f[i, j, k] = mapping[0]
            elif d[i, j, k] == d_max:
                f[i, j, k] = mapping[100]

# Print the arrays d and f
print("Array d:\n", d)
print("Array f:\n", f)




Array d:
 [[[0.96245132 0.68055031 0.12087584 0.40074488 0.13883561]
  [0.91391401 0.40807499 0.57186805 0.41883566 0.50648461]
  [0.02467561 0.95253588 0.66791113 0.93716958 0.42762517]]

 [[0.46912352 0.61671425 0.4195089  0.21373637 0.16030566]
  [0.61441736 0.32803941 0.44902273 0.09254363 0.64513218]
  [0.44860026 0.99667717 0.06605387 0.94816424 0.13603102]]]
Array f:
 [[['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['A' 'D' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'E' 'B' 'D' 'B']]]
