In [ ]:
#1. Import the NUMPY package under the name np.

In [3]:
import numpy as np

In [ ]:
#2. Print the NUMPY version and the configuration.

In [6]:
print(np.__version__)
print(np.show_config())

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
a = np.random.random((2, 3, 5))

In [ ]:
#4. Print a.

In [12]:
print(a)

[[[0.27152958 0.21638324 0.02249361 0.40841074 0.05259135]
  [0.73528536 0.10288035 0.99416958 0.85527053 0.31201346]
  [0.25150573 0.63258549 0.2311403  0.82091401 0.92960026]]

 [[0.3714682  0.95202361 0.6639422  0.076126   0.31077288]
  [0.36366045 0.48228551 0.69088927 0.81230203 0.98010445]
  [0.88121824 0.11593668 0.58063567 0.05459613 0.77894903]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [21]:
b = np.ones((5, 2, 3))

In [ ]:
#6. Print b.

In [22]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [44]:
print(a.size)
print(b.size)
if a.size == b.size:
    print("a array and b array have the same size")
else:
    print("a array and b array do not have the same size")

30
30
a array and b array have the same size


In [ ]:
#8. Are you able to add a and b? Why or why not?

In [45]:
c = a + b #No podemos sumar dos matrices con estructura(shape) diferente, para sumaralas deben compartir la misma estructura.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [67]:
print(b.shape)
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(5, 2, 3)
(2, 3, 5)


In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [70]:
d= a+c
print(d)

[[[1.27152958 1.21638324 1.02249361 1.40841074 1.05259135]
  [1.73528536 1.10288035 1.99416958 1.85527053 1.31201346]
  [1.25150573 1.63258549 1.2311403  1.82091401 1.92960026]]

 [[1.3714682  1.95202361 1.6639422  1.076126   1.31077288]
  [1.36366045 1.48228551 1.69088927 1.81230203 1.98010445]
  [1.88121824 1.11593668 1.58063567 1.05459613 1.77894903]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [72]:
print(a)   #Yes, the d array is the result of adding to the array a the array c that all the elements inside are ones so the d elements are the a elements plus one.


[[[0.27152958 0.21638324 0.02249361 0.40841074 0.05259135]
  [0.73528536 0.10288035 0.99416958 0.85527053 0.31201346]
  [0.25150573 0.63258549 0.2311403  0.82091401 0.92960026]]

 [[0.3714682  0.95202361 0.6639422  0.076126   0.31077288]
  [0.36366045 0.48228551 0.69088927 0.81230203 0.98010445]
  [0.88121824 0.11593668 0.58063567 0.05459613 0.77894903]]]


In [73]:
print(d)

[[[1.27152958 1.21638324 1.02249361 1.40841074 1.05259135]
  [1.73528536 1.10288035 1.99416958 1.85527053 1.31201346]
  [1.25150573 1.63258549 1.2311403  1.82091401 1.92960026]]

 [[1.3714682  1.95202361 1.6639422  1.076126   1.31077288]
  [1.36366045 1.48228551 1.69088927 1.81230203 1.98010445]
  [1.88121824 1.11593668 1.58063567 1.05459613 1.77894903]]]


In [ ]:
#12. Multiply a and c. Assign the result to e.

In [80]:
e = a*c
print(e)   

[[[0.27152958 0.21638324 0.02249361 0.40841074 0.05259135]
  [0.73528536 0.10288035 0.99416958 0.85527053 0.31201346]
  [0.25150573 0.63258549 0.2311403  0.82091401 0.92960026]]

 [[0.3714682  0.95202361 0.6639422  0.076126   0.31077288]
  [0.36366045 0.48228551 0.69088927 0.81230203 0.98010445]
  [0.88121824 0.11593668 0.58063567 0.05459613 0.77894903]]]


In [78]:
print(a)

[[[0.27152958 0.21638324 0.02249361 0.40841074 0.05259135]
  [0.73528536 0.10288035 0.99416958 0.85527053 0.31201346]
  [0.25150573 0.63258549 0.2311403  0.82091401 0.92960026]]

 [[0.3714682  0.95202361 0.6639422  0.076126   0.31077288]
  [0.36366045 0.48228551 0.69088927 0.81230203 0.98010445]
  [0.88121824 0.11593668 0.58063567 0.05459613 0.77894903]]]


In [79]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
#13. Does e equal to a? Why or why not?

In [ ]:
 #The array is the same because the values on a have been multiplied by an array that all values equal 1 and x*1 is x.

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [83]:
d_max = d.max()
print(d_max)
d_min= d.min()
print(d_min)
d_mean= d.mean()
print(d_mean)

1.994169580962922
1.0224936090114958
1.4983894647837632


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [111]:
f = np.empty((2, 3, 5))
print(f)

[[[1.27152958 1.21638324 1.02249361 1.40841074 1.05259135]
  [1.73528536 1.10288035 1.99416958 1.85527053 1.31201346]
  [1.25150573 1.63258549 1.2311403  1.82091401 1.92960026]]

 [[1.3714682  1.95202361 1.6639422  1.076126   1.31077288]
  [1.36366045 1.48228551 1.69088927 1.81230203 1.98010445]
  [1.88121824 1.11593668 1.58063567 1.05459613 1.77894903]]]


In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [117]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            valor = d[i][j][k]
            if d_min < valor and valor < d_mean:
                f[i][j][k] = 25
            elif d_mean < valor and valor < d_max:
                f[i][j][k] = 75
            elif valor == d_min:
                f[i][j][k] = 0
            elif valor == d_mean:
                f[i][j][k] = 50
            elif valor == d_max:
                f[i][j][k] = 100
            else:
                f[i][j][k] = valor 
        

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [118]:
print(d)
print(f)

[[[1.27152958 1.21638324 1.02249361 1.40841074 1.05259135]
  [1.73528536 1.10288035 1.99416958 1.85527053 1.31201346]
  [1.25150573 1.63258549 1.2311403  1.82091401 1.92960026]]

 [[1.3714682  1.95202361 1.6639422  1.076126   1.31077288]
  [1.36366045 1.48228551 1.69088927 1.81230203 1.98010445]
  [1.88121824 1.11593668 1.58063567 1.05459613 1.77894903]]]
[[[ 25.  25.   0.  25.  25.]
  [ 75.  25. 100.  75.  25.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""