In [69]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [70]:
#2. Print the NUMPY version and the configuration.

In [71]:
print("NumPy version:", np.__version__)

np.show_config()


NumPy version: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FX506/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FX506/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FX506/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FX506/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FX506/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FX506/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FX506/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/User

In [72]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [73]:
a = np.random.rand(2, 3, 5)

arr = np.random.random((2, 3, 5))

arr2 = np.random.randn(2, 3, 4)



In [74]:
#4. Print a.


In [75]:
print(a)

[[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]


In [76]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


In [77]:
b = np.ones((5, 2, 3))

In [78]:
#6. Print b.


In [79]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [80]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size)

print(b.size)





30
30


In [81]:
#8. Are you able to add a and b? Why or why not?


In [82]:
# no i can't add a and b because they have diferent shape, i could change the shape to do so.


In [83]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [84]:
c = b.T.reshape((2, 3, 5))

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [88]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= (a + c)

print(d)

[[[1.86206322 1.08761936 1.34872145 1.92723721 1.47793571]
  [1.35384118 1.7389423  1.92594774 1.70699174 1.35690313]
  [1.56298107 1.21071667 1.51783809 1.70862419 1.91691165]]

 [[1.04132088 1.48025259 1.93023528 1.69011651 1.54311274]
  [1.1218569  1.78468473 1.04334533 1.42524855 1.33048695]
  [1.74121912 1.18730936 1.60228446 1.81918088 1.53672891]]]


In [91]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print("this is the a array", a)



print("this is the d array", d)



this is the a array [[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]
this is the d array [[[1.86206322 1.08761936 1.34872145 1.92723721 1.47793571]
  [1.35384118 1.7389423  1.92594774 1.70699174 1.35690313]
  [1.56298107 1.21071667 1.51783809 1.70862419 1.91691165]]

 [[1.04132088 1.48025259 1.93023528 1.69011651 1.54311274]
  [1.1218569  1.78468473 1.04334533 1.42524855 1.33048695]
  [1.74121912 1.18730936 1.60228446 1.81918088 1.53672891]]]


In [ ]:
#The array "a" has values between 0 and 1, while the array "d" has the same values plus 1. This is because "d" was created by adding 1 to each element of "a". Therefore, "d" is a translation of "a" by a constant value of 1 in all dimensions. In other words, the relation between "a" and "d" is that "d" is a scalar addition of 1 to "a".

In [92]:
#12. Multiply a and c. Assign the result to e.

e = (a * c)

print(e)

[[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]


In [93]:
#13. Does e equal to a? Why or why not?

print(a)



print(e)




[[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]
[[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]


In [94]:
#Yes, e is equal to a.

#The reason is that e was created by assigning it the value of a using the assignment operator =. Since a was not modified after this assignment, e has the same values and dimensions as a.

In [95]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value: ", d_max)
print("Min value: ", d_min)
print("Mean value: ", d_mean)





Max value:  1.9302352820202398
Min value:  1.0413208761582302
Mean value:  1.5326885968644866


In [96]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [99]:
f = np.empty_like(d)

print(f)


[[[0.86206322 0.08761936 0.34872145 0.92723721 0.47793571]
  [0.35384118 0.7389423  0.92594774 0.70699174 0.35690313]
  [0.56298107 0.21071667 0.51783809 0.70862419 0.91691165]]

 [[0.04132088 0.48025259 0.93023528 0.69011651 0.54311274]
  [0.1218569  0.78468473 0.04334533 0.42524855 0.33048695]
  [0.74121912 0.18730936 0.60228446 0.81918088 0.53672891]]]


In [ ]:
#"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""