In [34]:
#1. Import the NUMPY package under the name np.

In [35]:
import numpy as np

In [36]:
#2. Print the NUMPY version and the configuration.

In [37]:
print("Versión de NumPy:", np.__version__)
print("\nConfiguración de NumPy:\n", np.show_config())


Versión de NumPy: 1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/javir/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/javir/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/javir/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/javir/anaconda3\\Library\\include']
Supported SIMD extensions i

In [38]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [39]:
# a = np.zeros((2, 3, 5))
# a = np.ones((2, 3, 5))
a = np.random.rand(2, 3, 5)

# 4. print(a)
print(a)

[[[0.63818951 0.67248745 0.40826031 0.83591088 0.94738436]
  [0.54405058 0.6347813  0.25215446 0.76122301 0.18950333]
  [0.95327449 0.52238867 0.17895155 0.24584271 0.90890372]]

 [[0.21691543 0.57530633 0.31681752 0.4285989  0.37539789]
  [0.5712383  0.75730803 0.98106594 0.2198275  0.52570964]
  [0.30809963 0.05957271 0.32200957 0.42059526 0.71400788]]]


In [40]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))


# 6. print(b)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [45]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size==b.size

True

In [54]:
#8. Are you able to add a and b? Why or why not?
suma_a_b= a + b

#Ambas matrices no pueden operarse ya que no tienen las mismas dimensiones, para ello habúa que trasponer alguna de ellas

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [68]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b, (1, 2, 0))
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [71]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c
print(d)

#gracias a la vectorización cada elemento del array se suma en una misma operación sin que tengamos que ir tratandolo de forma individual

[[[1.63818951 1.67248745 1.40826031 1.83591088 1.94738436]
  [1.54405058 1.6347813  1.25215446 1.76122301 1.18950333]
  [1.95327449 1.52238867 1.17895155 1.24584271 1.90890372]]

 [[1.21691543 1.57530633 1.31681752 1.4285989  1.37539789]
  [1.5712383  1.75730803 1.98106594 1.2198275  1.52570964]
  [1.30809963 1.05957271 1.32200957 1.42059526 1.71400788]]]


In [83]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

#La única diferencia se encuentra en el 1 que le hemos sumado, al sumarle 1 a todos los elementos del array hemos incrementado la longitud del vector en una unidad

[[[0.63818951 0.67248745 0.40826031 0.83591088 0.94738436]
  [0.54405058 0.6347813  0.25215446 0.76122301 0.18950333]
  [0.95327449 0.52238867 0.17895155 0.24584271 0.90890372]]

 [[0.21691543 0.57530633 0.31681752 0.4285989  0.37539789]
  [0.5712383  0.75730803 0.98106594 0.2198275  0.52570964]
  [0.30809963 0.05957271 0.32200957 0.42059526 0.71400788]]]
[[[1.63818951 1.67248745 1.40826031 1.83591088 1.94738436]
  [1.54405058 1.6347813  1.25215446 1.76122301 1.18950333]
  [1.95327449 1.52238867 1.17895155 1.24584271 1.90890372]]

 [[1.21691543 1.57530633 1.31681752 1.4285989  1.37539789]
  [1.5712383  1.75730803 1.98106594 1.2198275  1.52570964]
  [1.30809963 1.05957271 1.32200957 1.42059526 1.71400788]]]


In [85]:
#12. Multiply a and c. Assign the result to e.

e = a * c
print(e)

[[[0.63818951 0.67248745 0.40826031 0.83591088 0.94738436]
  [0.54405058 0.6347813  0.25215446 0.76122301 0.18950333]
  [0.95327449 0.52238867 0.17895155 0.24584271 0.90890372]]

 [[0.21691543 0.57530633 0.31681752 0.4285989  0.37539789]
  [0.5712383  0.75730803 0.98106594 0.2198275  0.52570964]
  [0.30809963 0.05957271 0.32200957 0.42059526 0.71400788]]]


In [88]:
#13. Does e equal to a? Why or why not?

e == a

#porque hemos multiplicado cada vector de a*1, a*1 = a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [91]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

print(d_max, d_min, d_mean)

1.9810659432136144 1.0595727142225637 1.5161925622346117


In [99]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty_like(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            f[i, j, k] = d[i, j, k] * 2

print(f)

[[[3.27637901 3.3449749  2.81652063 3.67182176 3.89476872]
  [3.08810115 3.26956259 2.50430892 3.52244602 2.37900666]
  [3.90654898 3.04477734 2.3579031  2.49168541 3.81780745]]

 [[2.43383086 3.15061266 2.63363504 2.8571978  2.75079579]
  [3.14247661 3.51461607 3.96213189 2.43965499 3.05141928]
  [2.61619926 2.11914543 2.64401914 2.84119052 3.42801575]]]


In [109]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

d = np.array(d)
f = np.zeros_like(d)

d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

f = np.zeros_like(f)

for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            else:
                f[i,j,k] = 100

print(f)



[[[ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  75. 100.  25.  75.]
  [ 25.   0.  25.  25.  75.]]]


In [111]:
# """
# #17. Print d and f. Do you have your expected f?
# For instance, if your d is:
# array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#         [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#         [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

#        [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#         [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#         [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Your f should be:
# array([[[ 75.,  75.,  75.,  25.,  75.],
#         [ 75.,  75.,  25.,  25.,  25.],
#         [ 75.,  25.,  75.,  75.,  75.]],

#        [[ 25.,  25.,  25.,  25., 100.],
#         [ 75.,  75.,  75.,  75.,  75.],
#         [ 25.,  75.,   0.,  75.,  75.]]])
# """
print(d)
print(f)

[[[1.63818951 1.67248745 1.40826031 1.83591088 1.94738436]
  [1.54405058 1.6347813  1.25215446 1.76122301 1.18950333]
  [1.95327449 1.52238867 1.17895155 1.24584271 1.90890372]]

 [[1.21691543 1.57530633 1.31681752 1.4285989  1.37539789]
  [1.5712383  1.75730803 1.98106594 1.2198275  1.52570964]
  [1.30809963 1.05957271 1.32200957 1.42059526 1.71400788]]]
[[[ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  75. 100.  25.  75.]
  [ 25.   0.  25.  25.  75.]]]


In [115]:
# """
# #18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.
# """


f = int(np.array(f))
g = int(np.zeros_like(f))

for i in range(g.shape[0]):
    for j in range(g.shape[1]):
        for k in range(g.shape[2]):
            if d[i,j,k] == 0:
                f[i,j,k] = 'A'
            elif d[i,j,k]== 25:
                f[i,j,k] = 'B'
            elif d[i,j,k] == 50:
                f[i,j,k] = 'C'
            elif d[i,j,k] == 75:
                f[i,j,k] = 'D'
            else:
                f[i,j,k] = 'E'

TypeError: only size-1 arrays can be converted to Python scalars