In [5]:
#1. Import the NUMPY package under the name np.
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [7]:
#2. Print the NUMPY version and the configuration.
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/monicaclaroscadima/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/monicaclaro

In [49]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
vector= np.random.random (9)
vector
3* vector
a =np.random.random ((2,3,5))


In [50]:
#4. Print a.
print (a)

[[[0.41321721 0.48844159 0.7230679  0.8426041  0.15973627]
  [0.23550551 0.54831916 0.28358776 0.80608038 0.04884096]
  [0.65528692 0.65936625 0.7700182  0.70690548 0.95102562]]

 [[0.83939506 0.80559324 0.55992965 0.01847998 0.21672256]
  [0.86441327 0.53681474 0.07001796 0.98787535 0.74774832]
  [0.2934333  0.05639684 0.75551065 0.90967047 0.83126899]]]


In [73]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b" ways can you find?
b = np.ones ((5, 2, 3))

In [74]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
#7. Do a and b have the same size? How do you prove that in Python code?
## se obtiene los tamaños (3,5) (2,3)
a.shape

(2, 3, 5)

In [76]:
b.shape

(5, 2, 3)

In [39]:
#8. Are you able to add a and b? Why or why not?

#R.- no se puede operar porque son de diferente tamaño   


In [82]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c"
c= b.transpose()

In [65]:
c.shape

(3, 2, 5)

In [84]:
c= c.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [89]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= np.add(a[0], c[1])

In [90]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
a

array([[[0.41321721, 0.48844159, 0.7230679 , 0.8426041 , 0.15973627],
        [0.23550551, 0.54831916, 0.28358776, 0.80608038, 0.04884096],
        [0.65528692, 0.65936625, 0.7700182 , 0.70690548, 0.95102562]],

       [[0.83939506, 0.80559324, 0.55992965, 0.01847998, 0.21672256],
        [0.86441327, 0.53681474, 0.07001796, 0.98787535, 0.74774832],
        [0.2934333 , 0.05639684, 0.75551065, 0.90967047, 0.83126899]]])

In [91]:
d

array([[1.41321721, 1.48844159, 1.7230679 , 1.8426041 , 1.15973627],
       [1.23550551, 1.54831916, 1.28358776, 1.80608038, 1.04884096],
       [1.65528692, 1.65936625, 1.7700182 , 1.70690548, 1.95102562]])

In [93]:
#12. Multiply a and c. Assign the result to e.
e= np.multiply(a[0], c[1])
e

array([[0.41321721, 0.48844159, 0.7230679 , 0.8426041 , 0.15973627],
       [0.23550551, 0.54831916, 0.28358776, 0.80608038, 0.04884096],
       [0.65528692, 0.65936625, 0.7700182 , 0.70690548, 0.95102562]])

In [94]:

#13. Does e equal to a? Why or why not?

In [95]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
np.inf

inf

In [98]:
d_min= d.min()
d_min

1.0488409628220428

In [99]:
d_max= d.max()
d_max

1.9510256170325126

In [100]:
d_mean= d.mean()
d_mean

1.552800221773243

In [102]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f= np.empty((2,3,5))
f

array([[[0.41321721, 0.48844159, 0.7230679 , 0.8426041 , 0.15973627],
        [0.23550551, 0.54831916, 0.28358776, 0.80608038, 0.04884096],
        [0.65528692, 0.65936625, 0.7700182 , 0.70690548, 0.95102562]],

       [[0.83939506, 0.80559324, 0.55992965, 0.01847998, 0.21672256],
        [0.86441327, 0.53681474, 0.07001796, 0.98787535, 0.74774832],
        [0.2934333 , 0.05639684, 0.75551065, 0.90967047, 0.83126899]]])