# 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.21.5


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# METHOD 1:
a = np.random.random((2, 3, 5))

# METHOD 2:
a = np.random.randn(2, 3, 5)

# METHOD 3:
a = np.random.randint(low=0, high=10, size=(2, 3, 5))

# 4. Print a.

In [10]:
print(a)

[[[0 2 7 1 5]
  [2 2 1 5 0]
  [1 5 9 8 8]]

 [[1 2 9 8 3]
  [6 2 0 0 1]
  [2 3 6 5 2]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [15]:
b = np.ones((5, 2, 3))

# 6. Print b.

In [19]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [22]:
np.size(a) == np.size(b)

print(a.size, b.size)

30 30


# 8. Are you able to add a and b? Why or why not?

In [23]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [28]:
c = b.transpose((1, 2, 0))

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [30]:
d = a + c

d

array([[[ 1.,  3.,  8.,  2.,  6.],
        [ 3.,  3.,  2.,  6.,  1.],
        [ 2.,  6., 10.,  9.,  9.]],

       [[ 2.,  3., 10.,  9.,  4.],
        [ 7.,  3.,  1.,  1.,  2.],
        [ 3.,  4.,  7.,  6.,  3.]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
print(a)

print(d)

'''
'a' contains random values between 0 and 1,
while 'd' contains the same values as 'a',
but with 1 added to each element.
This is because 'd' is the result of adding 'a' and 'c',
where 'c' is 'b' transposed to have the same shape as 'a'.
Since 'b' contains only 1s,
adding 'c' to 'a' effectively adds 1 to each element of 'a'.
'''

[[[0 2 7 1 5]
  [2 2 1 5 0]
  [1 5 9 8 8]]

 [[1 2 9 8 3]
  [6 2 0 0 1]
  [2 3 6 5 2]]]
[[[ 1.  3.  8.  2.  6.]
  [ 3.  3.  2.  6.  1.]
  [ 2.  6. 10.  9.  9.]]

 [[ 2.  3. 10.  9.  4.]
  [ 7.  3.  1.  1.  2.]
  [ 3.  4.  7.  6.  3.]]]


"\n'a' contains random values between 0 and 1,\nwhile 'd' contains the same values as 'a',\nbut with 1 added to each element.\nThis is because 'd' is the result of adding 'a' and 'c',\nwhere 'c' is 'b' transposed to have the same shape as 'a'.\nSince 'b' contains only 1s,\nadding 'c' to 'a' effectively adds 1 to each element of 'a'.\n"

# 12. Multiply a and c. Assign the result to e.

In [37]:
e = a * c

e

array([[[0., 2., 7., 1., 5.],
        [2., 2., 1., 5., 0.],
        [1., 5., 9., 8., 8.]],

       [[1., 2., 9., 8., 3.],
        [6., 2., 0., 0., 1.],
        [2., 3., 6., 5., 2.]]])

# 13. Does e equal to a? Why or why not?

In [39]:
e == a

'''
 e is equal to a.
 This is because we calculated e by multiplying a and c,
 where c is the transpose of b.
 However, we defined b as an array of ones,
 so the transpose of b is also an array of ones,
 and therefore the product of a and c is just a itself.

In other words,
each element in e is obtained by multiplying the corresponding element in a with 1,
since c is an array of ones.
So e has the exact same values as a.
'''

'\n e is equal to a.\n This is because we calculated e by multiplying a and c,\n where c is the transpose of b.\n However, we defined b as an array of ones,\n so the transpose of b is also an array of ones,\n and therefore the product of a and c is just a itself.\n\nIn other words,\neach element in e is obtained by multiplying the corresponding element in a with 1,\nsince c is an array of ones.\nSo e has the exact same values as a.\n'

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".

In [51]:
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [54]:
f = np.empty_like(d)

# 16. Populate the values in f.

For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [57]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100



# 17. Print d and f. Do you have your expected f?

In [58]:
print(d)

print(f)

[[[ 1.  3.  8.  2.  6.]
  [ 3.  3.  2.  6.  1.]
  [ 2.  6. 10.  9.  9.]]

 [[ 2.  3. 10.  9.  4.]
  [ 7.  3.  1.  1.  2.]
  [ 3.  4.  7.  6.  3.]]]
[[[  0.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.   0.]
  [ 25.  75. 100.  75.  75.]]

 [[ 25.  25. 100.  75.  25.]
  [ 75.  25.   0.   0.  25.]
  [ 25.  25.  75.  75.  25.]]]
