In [1]:
#1. Import the NUMPY package under the name np.

In [2]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.

In [5]:
print("NumPy version:", np.__version__)
print("\nNumPy configuration:\n", np.show_config())

NumPy version: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_di

In [6]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# a = np.random.random((2, 3, 5))

In [8]:
a = np.random.rand(2, 3, 5)

In [9]:
type(a)

numpy.ndarray

In [10]:
#4. Print a.

In [11]:
a

array([[[0.01084323, 0.68238073, 0.05298734, 0.49086066, 0.34914996],
        [0.74204823, 0.31232435, 0.32062715, 0.58412991, 0.66398752],
        [0.50860319, 0.63119115, 0.28460354, 0.80588577, 0.55515779]],

       [[0.70003051, 0.69056395, 0.99503626, 0.49409464, 0.61687835],
        [0.51782625, 0.18383961, 0.44552457, 0.61492126, 0.46763675],
        [0.68412168, 0.96344535, 0.53300163, 0.14629037, 0.69984004]]])

In [12]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [13]:
b = np.ones((5, 2, 3))

In [14]:
#6. Print b.

In [15]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [17]:
a.size == b.size

True

In [18]:
#8. Are you able to add a and b? Why or why not?

In [19]:
# I am not able to add a in b because the array at index 0 has size 3 and 
# the array at index 1 has size 2

In [20]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array).
# Assign the transposed array to varialbe "c".

In [21]:
a.shape

(2, 3, 5)

In [22]:
b.shape

(5, 2, 3)

In [23]:
c = np.reshape(b, (2, 3, 5))

In [24]:
c.shape

(2, 3, 5)

In [25]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [26]:
d = a + c

d

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [27]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [28]:
a

array([[[0.01084323, 0.68238073, 0.05298734, 0.49086066, 0.34914996],
        [0.74204823, 0.31232435, 0.32062715, 0.58412991, 0.66398752],
        [0.50860319, 0.63119115, 0.28460354, 0.80588577, 0.55515779]],

       [[0.70003051, 0.69056395, 0.99503626, 0.49409464, 0.61687835],
        [0.51782625, 0.18383961, 0.44552457, 0.61492126, 0.46763675],
        [0.68412168, 0.96344535, 0.53300163, 0.14629037, 0.69984004]]])

In [29]:
d

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [30]:
# The difference between 'a' and 'd' values are the sum of the array 'a' plus 'b' in 'd'.

In [31]:
#12. Multiply a and c. Assign the result to e.

In [32]:
a

array([[[0.01084323, 0.68238073, 0.05298734, 0.49086066, 0.34914996],
        [0.74204823, 0.31232435, 0.32062715, 0.58412991, 0.66398752],
        [0.50860319, 0.63119115, 0.28460354, 0.80588577, 0.55515779]],

       [[0.70003051, 0.69056395, 0.99503626, 0.49409464, 0.61687835],
        [0.51782625, 0.18383961, 0.44552457, 0.61492126, 0.46763675],
        [0.68412168, 0.96344535, 0.53300163, 0.14629037, 0.69984004]]])

In [33]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [34]:
e = a * c

In [35]:
e

array([[[0.01084323, 0.68238073, 0.05298734, 0.49086066, 0.34914996],
        [0.74204823, 0.31232435, 0.32062715, 0.58412991, 0.66398752],
        [0.50860319, 0.63119115, 0.28460354, 0.80588577, 0.55515779]],

       [[0.70003051, 0.69056395, 0.99503626, 0.49409464, 0.61687835],
        [0.51782625, 0.18383961, 0.44552457, 0.61492126, 0.46763675],
        [0.68412168, 0.96344535, 0.53300163, 0.14629037, 0.69984004]]])

In [36]:
#13. Does e equal to a? Why or why not?

In [37]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [38]:
#14. Identify the max, min, and mean values in d. Assign those values to variables 
# "d_max", "d_min", and "d_mean"

In [52]:
d

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [53]:
d_max = d.max()

d_max

1.9950362564281061

In [54]:
d_min = d.min()

d_min

1.0108432265174772

In [55]:
d_mean = d.mean()

d_mean

1.5249277247519415

In [56]:
#15. Now we want to label the values in d. First create an empty array "f" 
# with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [57]:
f = np.empty((2, 3, 5))

f

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [60]:
d

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [61]:
f

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [65]:
f[(d_mean > d) & (d > d_min)] = 25
f[(d_max > d) & (d > d_mean)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

f

array([[[  0.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  75.,  75.],
        [ 25.,  75.,  25.,  75.,  75.]],

       [[ 75.,  75., 100.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  75.,  25.,  75.]]])

In [66]:
#17. Print d and f. Do you have your expected f?

In [67]:
d

array([[[1.01084323, 1.68238073, 1.05298734, 1.49086066, 1.34914996],
        [1.74204823, 1.31232435, 1.32062715, 1.58412991, 1.66398752],
        [1.50860319, 1.63119115, 1.28460354, 1.80588577, 1.55515779]],

       [[1.70003051, 1.69056395, 1.99503626, 1.49409464, 1.61687835],
        [1.51782625, 1.18383961, 1.44552457, 1.61492126, 1.46763675],
        [1.68412168, 1.96344535, 1.53300163, 1.14629037, 1.69984004]]])

In [68]:
f

array([[[  0.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  75.,  75.],
        [ 25.,  75.,  25.,  75.,  75.]],

       [[ 75.,  75., 100.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  75.,  25.,  75.]]])

In [69]:
# Yes it worked.

In [70]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements?

In [76]:
f_str = f.astype(str)

f_str[(d_mean > d) & (d > d_min)] = 'B'
f_str[(d_max > d) & (d > d_mean)] = 'D'
f_str[(d == d_mean)] = 'C'
f_str[(d == d_min)] = 'A'
f_str[(d == d_max)] = 'E'

f_str

array([[['A', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'D', 'D'],
        ['B', 'D', 'B', 'D', 'D']],

       [['D', 'D', 'E', 'B', 'D'],
        ['B', 'B', 'B', 'D', 'B'],
        ['D', 'D', 'D', 'B', 'D']]], dtype='<U32')